---
- name: PostgreSQL 12
  hosts: hadoop
  become: yes
  tasks:
  - name: Instalar postgresql no Ubuntu
    apt:
      name: postgresql-12
      state: latest
  - name: Iniciar serviço
    ansible.builtin.service:
      name: postgresql
      state: started
